language: cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
  - sudo apt-get install -y autoconf libtool cmake make psmisc build-essential
  - sudo apt-get install -y libpam0g-dev libssl-dev libgtest-dev  
  - sudo apt-get install -y flex bison libwrap0-dev

script:
  - mkdir -p /tmp/gtest && cd /tmp/gtest
  - git clone https://github.com/google/googletest.git
  - cd googletest && cmake . && make && sudo make install
  - cd ~ 
  - git clone https://github.com/pttch/sonic-pam-tacacs-dev.git  
  - cd sonic-pam-tacacs-dev  
  - git submodule init  
  - git submodule update
  - cd ~/sonic-pam-tacacs-dev  
  - ./build.sh  
  - mkdir build 
  - cd build  
  - cmake ../ -DSERVER_BIN_PATH=`pwd`/../server/sbin/ -DSERVER_PORT=4900  
  - make 
  - ~/sonic-pam-tacacs-dev/build/pam_tacplus_integration_test
  - ~/sonic-pam-tacacs-dev/build/pam_tacplus_unit_test  
  - lsb_release -a
